name: Nightly Delivery

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  Publish:
    name: Publish nightly version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          fetch-depth: 0
          ref: 'rewrite'
      - name: Add TypeScript problem matcher
        run: echo "::add-matcher::.github/problemMatchers/tsc.json"
      - name: Use Node.js v16
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3
        with:
          node-version: 16
          cache: yarn
          registry-url: https://registry.npmjs.org/
      - name: Install Dependencies
        run: yarn --immutable
      - name: Build project
        run: yarn build:prod
      - name: Bump Version & Publish
        run: |
          # Bump the version
          yarn version:nightly
          # Publish to NPM
          npm publish --tag nightly --dry-run || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NIGHTLY_NPM_TOKEN }}
