name: Nightly Delivery

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  Publish:
    name: Publish nightly version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3
        with:
          fetch-depth: 0
          ref: 'rewrite'
      - name: Add TypeScript problem matcher
        run: echo "::add-matcher::.github/problemMatchers/tsc.json"
      - name: Use Node.js v16
        uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a # tag=v3
        with:
          node-version: 16
          cache: yarn
          registry-url: https://registry.npmjs.org/
      - name: Install Dependencies
        run: yarn --immutable
      - name: Build project
        run: yarn build:prod
      - name: Bump Version & Publish
        run: |
          # Bump the version
          yarn version:nightly
          # Publish to NPM
          npm publish --tag nightly --dry-run || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NIGHTLY_NPM_TOKEN }}
